#!/usr/bin/env bash
# Fizzbuzz script
i=1
while [ $i -le 100 ]
do 
if (( i%15 == 0)); then
printf "FizzBuzz\n"
elif (( i%3 == 0)); then
printf "Fizz\n"
elif (( i%5 == 0)); then
printf "Buzz\n"
else 
printf "%s$i\n"
fi
((i++))
done
