#!/usr/bin/env bash
# Superstitous script
i=1
while [ $i -le 20 ]
do 
case $i in
4) printf "$i\n bad luck from China\n"
;;
9) printf "$i\n bad luck from Japan\n"
;;
17) printf "$i\n bad luck from Italy\n"
;;
*) printf "$i\n"
;;
esac
((i++))
done 
