#!/usr/bin/env bash
# Superstitous script
i=1
while [ $i -le 20 ]
do 
case $i in
4) printf "%s$i\nbad luck from China\n"
;;
9) printf "%s$i\nbad luck from Japan\n"
;;
17) printf "%s$i\nbad luck from Italy\n"
;;
*) printf "%s$i\n"
;;
esac
((i++))
done 
