#!usr/bin/env bash
# Description of a file
if [ -e school ]; then
printf "school file exists\n"
if [ -s school ]; then 
printf "school is not empty\n"
else 
printf "school is empty\n"
fi
else 
printf "school file does not exist\n"
fi
if [ -f school ]; then
printf "school is a regular file\n"
fi
