#!/usr/bin/env bash
# Process, pid and file

trap " echo 'Y U no love me?!' " SIGINT
trap " echo 'I hate the kill command'; rm -f /var/run/myscript.pid  " SIGTERM
trap " rm -f /var/run/myscript.pid " SIGQUIT

echo $$ >> /var/run/myscript.pid

while (true)
do 
echo "To infinity and beyond"
sleep 2
done
